### ISSUE TITLE
Google Meet sometimes stuck on verify screen

### ISSUE THREAD

**Issue by behoyh** [pmansour/minimeet#7]
Sometimes, minimeet does not advance past a Google auth screen called "verify your identity" there is a single button on this page so a carriage return or click should fix.

**Comment by pmansour** [comment]
I attempted to fix this a few months ago with https://github.com/pmansour/minimeet/commit/9f9f2459d742fdf8fed21f019f5c1b445c17bfaa. Can you update your extension (e.g. by running [`update-extension.sh`](https://github.com/pmansour/pimeet/blob/master/scripts/update-extension.sh) from the pimeet repo) and try again, and let me know if this is happening? You'll want to be on version 1.2.1 or above.

**Comment by behoyh** [comment]
Just installed the patch, will update once I can confirm fix.

**Comment by behoyh** [comment]
I'm gonna close this for now
